<?php

const DEFAULT_TERMINAL_WIDTH = 120;
const DEFAULT_TERMINAL_HEIGHT = 30;
const MIN_TERMINAL_WIDTH = 80;
const MIN_TERMINAL_HEIGHT = 24;
const DEFAULT_DIALOG_WIDTH = 50;
const DEFAULT_DIALOG_HEIGHT = 3;
